# Generated by Django 4.2.6 on 2023-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLettercontract',
            fields=[
                ('candidateid', models.IntegerField(primary_key=True, serialize=False)),
                ('offredcompany', models.CharField(max_length=50)),
                ('offerdate', models.DateField(auto_now=True)),
                ('candidatename', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('projectname', models.CharField(max_length=100)),
                ('contractstart', models.CharField(max_length=10)),
                ('contractend', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OfferLetterfulltime',
            fields=[
                ('candidateid', models.IntegerField(primary_key=True, serialize=False)),
                ('offredcompany', models.CharField(max_length=50)),
                ('offerdate', models.DateField(auto_now=True)),
                ('candidatename', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('projectname', models.CharField(max_length=100)),
                ('contractstart', models.CharField(max_length=10)),
                ('contractend', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
