# Generated by Django 4.2.6 on 2023-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettercontract',
            name='emialid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offerlettercontract',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offerletterfulltime',
            name='emialid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offerletterfulltime',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='candidatename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='contractend',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='contractstart',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='offerdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='offredcompany',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='projectname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettercontract',
            name='salary',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='candidatename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='contractend',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='contractstart',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='offerdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='offredcompany',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='projectname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerletterfulltime',
            name='salary',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
