# Generated by Django 4.2.6 on 2023-12-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Application', '0003_delete_offerletterfulltime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerlettercontract',
            old_name='contractstart',
            new_name='joining',
        ),
    ]
